domain_name_list: ['beauty']
user_threshold: 5
item_threshold: 5
max_seq_len: 50
dataset_class: 'general'
train_file: '_gene-pair2-5'
# train_file: '_gene-generative1-1'
# train_file: '_gene-real2'
# train_file: '_gene-pair2-5'
# train_file: '_gene-K7'