model:
  hidden_size: 128
  layer_num: 2
  head_num: 2
  dropout_rate: 0.5
  activation: 'gelu'
  layer_norm_eps: 1.0e-12
  augment_type: 'item_random'
  temperature: 1.0
  cl_weight: 0.1

  # toy & beauty
  # tau: 0.2
  # gamma: 0.7
  # beta: 0.2

  # sport
  tau: 0.4
  gamma: 0.4
  beta: 0.2
  
  # yelp
  # tau: 0.4
  # gamma: 0.7
  # beta: 0.2

