model:
  hidden_size: 128
  layer_num: 2
  head_num: 2
  dropout_rate: 0.5
  activation: 'gelu'
  layer_norm_eps: 1.0e-12
  uniformity: 1
  K: 128
  depth: 1


train:
  warmup_epoch: -1
  # learning_rate: 2.e-3